version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - '6379:6379'
    networks:
      - app-network
    volumes:
      - redis-data:/data
    command: ['redis-server', '--appendonly', 'yes']

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
